In [1]:
import torch

In [3]:
a = torch.ones([2,5])

In [3]:
N = 2
L = 5
noise = torch.rand(N, L); print(noise)

tensor([[0.2855, 0.2364, 0.2049, 0.6593, 0.1206],
        [0.5410, 0.2888, 0.8693, 0.5312, 0.8782]])


In [7]:
ids_shuffle = torch.argsort(noise, dim=1); print(ids_shuffle)

tensor([[4, 2, 1, 0, 3],
        [1, 3, 0, 2, 4]])


In [6]:
torch.argsort(ids_shuffle, dim=1)

tensor([[3, 2, 1, 4, 0],
        [2, 0, 3, 1, 4]])

In [8]:
x = torch.tensor([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [10]:
torch.gather(x, dim=1, index=ids_shuffle)

tensor([[ 5,  3,  2,  1,  4],
        [ 7,  9,  6,  8, 10]])

In [2]:
"checkpoint-%s-%s" % ('10', '20')

'checkpoint-10-20'