In [1]:
import torch

In [3]:
a = torch.ones([2,5])

In [3]:
tuple(2)

TypeError: 'int' object is not iterable

In [21]:
import torch 
from torch import nn as nn

In [20]:
name = 'Bob'
age = 17
'name: %s' % name
'name: %(name)s, age: %(age)d' % {"name": name, "age": age}

'name: Bob, age: 17'

In [1]:
class Car(object):
    def __init__(self):
        self.total = 0.0
        self.count = 0

motor = Car()

In [5]:
def create_adder(x):
    def adder(y):
        return x+y
 
    return adder
 
add_15 = create_adder(15)
 
print(add_15(10))

25


In [20]:
# importing libraries
import time
import math
 
# decorator to calculate duration
# taken by any function.
def calculate_time(func):
     
    # added arguments inside the inner1,
    # if function takes any arguments,
    # can be added like this.
    def inner1(*args, **kwargs):
 
        # storing time before function execution
        begin = time.time()
         
        output = func(*args, **kwargs)
 
        # storing time after function execution
        end = time.time()
        print("Total time taken in : ", func.__name__, end - begin)
        
        return output
 
    return inner1
 
 
 
# this can be added to any function present,
# in this case to calculate a factorial
@calculate_time
def factorial(num):
 
    # sleep 2 seconds because it takes very less time
    # so that you can see the actual difference
    time.sleep(2)
    print(math.factorial(num))

    return 5
 
# calling the function.
b = factorial(10)

3628800
Total time taken in :  factorial 2.0021753311157227


In [21]:
b

5

In [12]:
a = 6
def func(x):
    a = a * x
    print(a)
    return a
print(a)
func(5)

6


UnboundLocalError: local variable 'a' referenced before assignment

In [6]:
add_15

<function __main__.create_adder.<locals>.adder(y)>

In [4]:
bb = motor
bb

In [31]:
name = 'Bob'
a = 10
b = 7

# f'Hello, {name}'
# f'Hello, {name}, your are {a+b} years old.'
f'Hello, {name:s}, your are {a+b:.4f} years old.'

'Hello, Bob, your are 17.0000 years old.'

In [23]:
name = 'Bob'
age = 17

# 'Hello, {}'.format(name)
# 'Hello, {name}, your are {age} years old.'.format(name=name, age=age)
'Hello, {name:s}, your are {age:d} years old.'.format(name=name, age=age)

'Hello, Bob, your are 17 years old.'

In [17]:
name = 'bob'
'name:%s' % name

'name:bob'

In [22]:
proj = nn.Conv2d(3, 768, kernel_size=(16,16), stride=(16,16))

In [23]:
bias = proj.bias

In [25]:
bias.shape

torch.Size([768])

In [32]:
layernorm = nn.BatchNorm2d(768)

In [34]:
layernorm.bias.shape

torch.Size([768])

In [2]:
w = proj.weight

In [7]:
w.shape

torch.Size([768, 3, 16, 16])

In [38]:
noise = torch.rand(2, 3)
ids_shuffle = torch.argsort(noise, dim=1)
ids_restore = torch.argsort(ids_shuffle, dim=1)

In [39]:
noise

tensor([[0.0634, 0.4059, 0.5383],
        [0.8162, 0.4557, 0.6871]])

In [51]:
a = torch.tensor([x for x in range(12)], dtype=float).view(3, 2, 2)

In [52]:
a

tensor([[[ 0.,  1.],
         [ 2.,  3.]],

        [[ 4.,  5.],
         [ 6.,  7.]],

        [[ 8.,  9.],
         [10., 11.]]], dtype=torch.float64)

In [53]:
a.mean(dim=1)

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]], dtype=torch.float64)

In [40]:
ids_shuffle

tensor([[0, 1, 2],
        [1, 2, 0]])

In [41]:
ids_restore

tensor([[0, 1, 2],
        [2, 0, 1]])

In [8]:
y = w.data

In [10]:
y.shape

torch.Size([768, 3, 16, 16])

In [18]:
w = nn.Parameter(torch.zeros(2,2))

In [20]:
w.data

tensor([[0., 0.],
        [0., 0.]])

In [11]:
type(w)

torch.nn.parameter.Parameter

In [12]:
type(y)

torch.Tensor

In [15]:
proj.requires_grad_()

Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16))

In [ ]:
torch.nn.parameter.Parameter

In [5]:
from itertools import repeat

tuple(repeat(3, 4))

(3, 3, 3, 3)

In [3]:
N = 2
L = 5
noise = torch.rand(N, L); print(noise)

tensor([[0.2855, 0.2364, 0.2049, 0.6593, 0.1206],
        [0.5410, 0.2888, 0.8693, 0.5312, 0.8782]])


In [7]:
ids_shuffle = torch.argsort(noise, dim=1); print(ids_shuffle)

tensor([[4, 2, 1, 0, 3],
        [1, 3, 0, 2, 4]])


In [6]:
torch.argsort(ids_shuffle, dim=1)

tensor([[3, 2, 1, 4, 0],
        [2, 0, 3, 1, 4]])

In [8]:
x = torch.tensor([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [10]:
torch.gather(x, dim=1, index=ids_shuffle)

tensor([[ 5,  3,  2,  1,  4],
        [ 7,  9,  6,  8, 10]])

In [2]:
"checkpoint-%s-%s" % ('10', '20')

'checkpoint-10-20'